export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_BONUS_LIST_SUCCESS = 'UPDATE_BONUS_LIST_SUCCESS';
export const UPDATE_BONUS_LIST_ERROR = 'UPDATE_BONUS_LIST_ERROR';
export const UPDATE_BONUS_LIST_LOADING = 'UPDATE_BONUS_LIST_LOADING';
