export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_BONUS_LIST = 'UPDATE_BONUS_LIST';
export const UPDATE_BONUS_LIST_ERROR = 'UPDATE_BONUS_LIST_ERROR';
export const UPDATE_BONUS_LIST_LOADING = 'UPDATE_BONUS_LIST_LOADING';
